#+title: Daily work log for Ian Galvin Fernandes

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?  
     I was assigned the task of familiarizing myself with 
     the Emacs environment and IDE. I had to familiarize myself with the common
     commands used in Emacs and use those commands extensively while
     working with Emacs.

   + What did I get done against each task?
     I spent time familiarizing myself with most of the common
     commands, and used them repetitively, until I was able to use
     these commands with ease.

** [2016-05-17 Tue]
   + What was the task I was assigned today?
     -We have to set constraints for the deleteUser method for the web application
     -We have to create a relational data model for a web application

   + What did I get done against each task?
     -For the deleteUser method, I set the relational constraints, along with
     with other required constraints.
     -For the relational data model, we have worked on organizing the
     requirements into the relational requirements, type requirements,
     entity requirements, etc. After segregation, we edited the requirements
     document to highlight the requirements for the web application.

** [2016-05-18 Wed]
   + What was the task I was assigned today?
     - We had to complete the object model for the given web application, and
       work on the object relational model. This task involved completion of
       definition of objects, along with function definitions and running of
       test cases.

   + What did I get done against the task?
     - We completed the object model, and defined appropriate test cases for
       the object methods, so as to ensure that the methods ran as designed.

** [2016-05-19 Thu]
   + What was the task I was assigned today?
     - We had to add the Session entity to the object model, for the given web
       application, and complete the operations for the new, modified object
       relational model, along with function definitions and running of test
       cases.
       
   + What did I get done against the task?
     - We completed the addition of the Session object, to the object model,
       and added the required operations and corresponding test cases, in order
       to ensure that the methods ran as designed.

** [2016-05-20 Fri]
   + What was the task I was assigned today?
     - We had to add the System entity to the object model, for the given web
       application, and complete the operations for the new, modified object
       model, along with function definitions and running of test cases.
       
   + What did I get done against the task?
     - We completed the addition of the System class, to the object model,
       and added the required operations and corresponding test cases, in order
       to ensure that the methods ran as designed.

** Weekly  Summary
   + What are the insights gained?
     - So far, I have learnt how to build an Object Model in accordance with a
       Data model, in order to complete the the object section of an application.
   + What is my footprint in the realization of the project?
     - As of now, I can build an Object Model, in accordance with a Data Model,
       for a given application. So, in this sense, I feel that I can build the
       object-related section of an application.


** [2016-05-23 Mon]

    + What was the task I was assigned today?
     - We had to create the Object Relational Model, and add the appropriate
       methods and test cases, in order to complete the ORM.
       
    + What did I get done against the task?
     - We added the ORM boiler-plate code, and began work on the addition and
       modification of new/existing methods and their corresponding test cases.

** [2016-05-24 Tue]

    + What was the task I was assigned today?
      - I had to update the ORM by adding the System class, and add the appropriate
       methods and test cases, in order to complete it.
       
    + What did I get done against the task?
     - I added the System class from the existing Object Model to ORM boiler-plate code, and began work on the addition and
       modification of new/existing methods and their corresponding test cases.

** [2016-05-25 Wed]

    + What was the task I was assigned today?
     - I had to build the REST API for the given web application, by referring
        to the functionality of the ORM.
       
    + What did I get done against the task?
     - I worked on the boilerplate code template provided for the REST API, and added the
       required functionality.

** [2016-05-26 Thu]

    + What was the task I was assigned today?
     - I had to update the REST API for the given web application, by
       implementing the System class methods in the API, so as to ensure that
       the System class acts as a controller.
       
    + What did I get done against the task?
     - I added the required functionality from the System class into the REST
       API and implemented the System class methods wherever possible/required.

** [2016-05-27 Fri]

    + What was the task I was assigned today?
     - I had to work on the View for the given web application, by
       implementing the given boilerplate code and adding the respective routing requests.
       
    + What did I get done against the task?
     - I added the boilerplate code and added the required routing
       functionality, so that the requests from the View can communicate with
       the Controller

** Weekly  Summary
   + What are the insights gained?
     - So far, I have learnt how to build the Object relational Model, the
       corresponding REST API for the ORM and the front-end View.
   + What is my footprint in the realization of the project?
     - As of now, I can build an Object Relational Model and the corresponding
       REST API, in accordance with a Data Model,
       for a given application. So, in this sense, I feel that I can build the
       model, controller and view (MVC) for a given application.
       

** [2016-05-30 Mon]

    + What was the task I was assigned today?
     - I had to work on completing the View for the given web application, by
       implementing and adding the respective routing requests.
       
    + What did I get done against the task?
     - I worked on the required routing functionality, so that the requests
       from the View can communicate with the Controller.

** [2016-05-31 Tue]

    + What was the task I was assigned today?
     - I was on leave on this day.
       
    + What did I get done against the task?
     - N/A

* Month of June
** [2016-06-01 Wed]

    + What was the task I was assigned today?
     - Today, we had to complete the front-end view for the given web
       application, with complete functionality.

    + What did I get done against the task?
     - I completed the functionality for the front-end by adding the add-user,
       delete-user and edit-user functionality for the front-end. 
       
** [2016-06-02 Thu]

    + What was the task I was assigned today?
     - Today, we had to deploy the completed application using an external
       server, both manually and using an ADS (Auto Deployment Services).

    + What did I get done against the task?
     - I completed the front-end section of the application and deployed the
       same on an external host, using both a manual deployment and an ADS. 
       
** [2016-06-03 Fri]

    + What was the task I was assigned today?
     - Today, we had to give a small presentation on the completed web
       application, and present the completed documentation on the same.

    + What did I get done against the task?
     - I presented the documentation on the completed web application, and
       demonstrated the working of the application, along with displaying the
       running test cases. 
       
** [2016-06-04 Sat]

    + What was the task I was assigned today?
     - Today, I had to read through the documentation of the existing outreach
       portal, so as to be able to prepare the data model for the same.
       

    + What did I get done against the task?
     - I read and understood the documentation for the outreach portal, and
       began implementation of the data model for the same.
              
** Weekly  Summary
   + What are the insights gained?
     - So far, I have learnt how to build a complete, end-to-end web
       application, along with manual and automatic deployment of the same,
       using the ADS (Auto Deployment Service) on the VLABS network.

   + What is my footprint in the realization of the project?
     - As of now, I have completed the building and deployment of an end-to-end
       web application, along with the deployment of the same.


** [2016-06-06 Mon]

    + What was the task I was assigned today?
     - Today, we had to work on preparing the data model for the already
       existing outreach portal.

    + What did I get done against the task?
     - I prepared the data model for the currently deployed outreach portal.
              
** [2016-06-07 Tue]

    + What was the task I was assigned today?
     - Today, I had to implement an Audit (logging system) on our user
       directory application, so as to implement the same for the outreach portal.
       

    + What did I get done against the task?
     - I began implementation of the Audit system in our user directory application.
              
** [2016-06-08 Wed]

    + What was the task I was assigned today?
     - Today, I had to complete the implementation of the Audit logging system
       on the user directory web application.
       
       
    + What did I get done against the task?
     - I completed the implementation of the Audit logging system on the user
       directory web application and wrote the required test cases for the same.
              
** [2016-06-09 Thu]

    + What was the task I was assigned today?
     - Today, I had to read the documentation for OpenID, and understand its
       working, so as to be able to implement it in the outreach portal.
       
       
    + What did I get done against the task?
     - I read the documentation for OpenID, and worked on the design and 
       implementation of the same on the user directory application that we built.
       
** [2016-06-10 Fri]

    + What was the task I was assigned today?
     - Today, I had to look for alternatives to using OpenID for authentication
       in the outreach portal.
                     
    + What did I get done against the task?
     - I read the documentation for other external authentication APIs, such as
       OAuth.
       
** Weekly  Summary
   + What are the insights gained?
     - So far, I've learned the process of building a complete, end-to-end
       application, along with understanding the intricacies of the
       process. I've also learned the proper method of coming up with proper
       documentation for a web application, and how to follow the models
       effectively in order to realize the project.
   + What is my footprint in the realization of the project?
     - As of now, we have completed the documentation of the data model of
       the existing outreach portal, and begun coding a few necessary modules
       that need to be implemented in the new outreach portal. 


** [2016-06-13 Mon]

    + What was the task I was assigned today?
     - Today, I had to read through the documentation for user authentication using
       Google APIs.              
    + What did I get done against the task?
     - I read and understood the methods of user authentication using the
       Google API and collaborated with other project team members in the
       realization of the same.

** [2016-06-14 Tue]

    + What was the task I was assigned today?
     - Today, I had to collaborate with Thirumal and work on implementation of
       existing modules on a web application, so as to further implement these
       in the outreach portal.              
    + What did I get done against the task?
     - I worked with Thirumal and we wrote the implementations as well as test
       cases for the modules. 
** [2016-06-15 Wed]

    + What was the task I was assigned today?
     - Today, we had to begin implementation of the new outreach portal model.             
    + What did I get done against the task?
     - We started building the data-model for the new outreach portal. 
** [2016-06-16 Thu]

    + What was the task I was assigned today?
     - Today, we had to work on writing the data-model for the new outreach portal.
    + What did I get done against the task?
     - We started writing the data-model for the outreach portal.
** [2016-06-17 Fri]

    + What was the task I was assigned today?
     - Today, we had to start building the object implementation for the
       outreach portal.
    + What did I get done against the task?
     - I referred to the existing as well as a newer implementation of the user
       directory application, shared by Thirumal, and began work on the object
       implementation of the outreach portal.
** Weekly  Summary
   + What are the insights gained?
     - So far, along with learning how to build a complete end-to-end web
       application, I've also learnt the proper steps involved in the
       completion of the object level implementation of such an application.    
   
   + What is my footprint in the realization of the project?
     - AS of now, we have written the documentation for first phase of the
       new outreach portal and have begun work on the object implementation.


** [2016-06-20 Mon]

    + What was the task I was assigned today?
     - Today, we had to start working on the object implementation of the
       outreach portal.
    + What did I get done against the task?
     - I began working on the object level implementation of the outreach
       portal.

** [2016-06-21 Tue]

    + What was the task I was assigned today?
     - Today, we had to define the data-model for the second phase of the
       outreach portal.
    + What did I get done against the task?
     - I worked with Sripathi and wrote the data-model and drew the necessary
       relation diagrams for the second phase and added it to the existing 
       data-model for the outreach portal. 

** [2016-06-22 Wed]

    + What was the task I was assigned today?
     - Today, we had to write the possible operations for the Workshop entity
       in the data-model and draw the workflow diagram for the same.
    + What did I get done against the task?
     - I worked with Sripathi and wrote the operations for the Workshop entity,
       along with the workflow diagram, and added it to the existing 
       data-model for the outreach portal. 

* Month of July
