#+title: Daily work log for Ian Galvin Fernandes

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?  
     I was assigned the task of familiarizing myself with 
     the Emacs environment and IDE. I had to familiarize myself with the common
     commands used in Emacs and use those commands extensively while
     working with Emacs.

   + What did I get done against each task?
     I spent time familiarizing myself with most of the common
     commands, and used them repetitively, until I was able to use
     these commands with ease.

** [2016-05-17 Tue]
   + What was the task I was assigned today?
     -We have to set constraints for the deleteUser method for the web application
     -We have to create a relational data model for a web application

   + What did I get done against each task?
     -For the deleteUser method, I set the relational constraints, along with
     with other required constraints.
     -For the relational data model, we have worked on organizing the
     requirements into the relational requirements, type requirements,
     entity requirements, etc. After segregation, we edited the requirements
     document to highlight the requirements for the web application.

** [2016-05-18 Wed]
   + What was the task I was assigned today?
     - We had to complete the object model for the given web application, and
       work on the object relational model. This task involved completion of
       definition of objects, along with function definitions and running of
       test cases.

   + What did I get done against the task?
     - We completed the object model, and defined appropriate test cases for
       the object methods, so as to ensure that the methods ran as designed.

** [2016-05-19 Thu]
   + What was the task I was assigned today?
     - We had to add the Session entity to the object model, for the given web
       application, and complete the operations for the new, modified object
       relational model, along with function definitions and running of test
       cases.
       
   + What did I get done against the task?
     - We completed the addition of the Session object, to the object model,
       and added the required operations and corresponding test cases, in order
       to ensure that the methods ran as designed.

** [2016-05-20 Fri]
   + What was the task I was assigned today?
     - We had to add the System entity to the object model, for the given web
       application, and complete the operations for the new, modified object
       model, along with function definitions and running of test cases.
       
   + What did I get done against the task?
     - We completed the addition of the System class, to the object model,
       and added the required operations and corresponding test cases, in order
       to ensure that the methods ran as designed.

** Weekly  Summary
   + What are the insights gained?
     - So far, I have learnt how to build an Object Model in accordance with a
       Data model, in order to complete the the object section of an application.
   + What is my footprint in the realization of the project?
     - As of now, I can build an Object Model, in accordance with a Data Model,
       for a given application. So, in this sense, I feel that I can build the
       object-related section of an application.
** [2016-05-23 Mon]

    + What was the task I was assigned today?
     - We had to create the Object Relational Model, and add the appropriate
       methods and test cases, in order to complete the ORM.
       
    + What did I get done against the task?
     - We added the ORM boiler-plate code, and began work on the addition and
       modification of new/existing methods and their corresponding test cases.

* Month of June
* Month of July
